### ISSUE TITLE
Building a drum-kit webpage using JavaScript

### ISSUE THREAD

**Issue by sandip2224** [Crio-Bytes/Web#27]
**MicroByte Title:** Building a drum-kit webpage using JavaScript

**Domains:**

- HTML markup
- CSS styling
- JavaScript functions

**Scope of learning for learners:**

- Frontend web development  
- CSS image styling  
- JavaScript DOM EventListener  

**Activities:**

- Utilising HTML buttons to represent drum accessories  
- Implementing CSS styling  
- Adding JavaScript DOM EventListener to HTML markup
- Deploying webpage to production

**Comment by sudhanshutiwari264** [comment]
@sandip2224 looks good to me as the topic picked by you is quite interesting!
Go ahead with the issue. Maintain the folder structure as mentioned by opening the correct PR and making a good one.
All the best
