### ISSUE TITLE
[Learners] Build a horizontal table and add it to the existing content

### ISSUE THREAD

**Issue by sandip2224** [Crio-Bytes/Web#28]
**MicroByte Title:** HTML Tables

**Improvement Proposal:** 

The content of [HTML Tables](https://github.com/Crio-Bytes/Web/tree/main/HTML%20Tables) microbyte can be made richer by adding a variation of the existing table (i.e. a horizontal table) with proper documentation under a separate folder. 
Here's a preview of how it's supposed to look:  

![1](https://user-images.githubusercontent.com/61842142/96823913-33420700-144b-11eb-80aa-d96f5c755c5c.PNG)

**Benefits of proposed improvements:** 

Learners will gain confidence in working with variations of HTML tables under requisite circumstances and gain confidence in building tables on their own.

**Comment by amoghrajesh** [comment]
Hey @sandip2224 the words "horizontal table" might be hard to understand for some people. 
Could you grab some screenshot online that best matches your issue and attach it to the description?

**Comment by sandip2224** [comment]
> Hey @sandip2224 the words "horizontal table" might be hard to understand for some people.
> Could you grab some screenshot online that best matches your issue and attach it to the description?

Done

**Comment by sg23600** [comment]
I am interested to work on this issue.

**Comment by amoghrajesh** [comment]
Sure @sg23600, go ahead. Assigning it to you
