### ISSUE TITLE
Building a responsive website design using flexbox

### ISSUE THREAD

**Issue by sandip2224** [Crio-Bytes/Web#7]
**Microbyte title**: Building responsive website layout using flexbox

**Domains covered:**  

- HTML markup<br/>
- CSS flexbox<br/>

**Scope of learning for learners:**  

- Responsive website design  
- HTML positioning using flexbox  
- Website layout design  
- Frontend web development 

**Activities:**  

- Building basic website **layout**  
- Implementing basic flexbox properties    
- Utilising media queries

**Comment by sudhanshutiwari264** [comment]
Make sure you follow the proper workflow. Don't make it too lengthy(max 1hr) and also don't make it tutorialish. Give room for contributors to contribute to your repo !

**Comment by sudhanshutiwari264** [comment]
@sandip2224 
For activities, you should add bullet points, like:

Activities:

- Activity1
- Activity2
- Activity3
Follow the same for scope of learning for learners. Also add a short description, like a one-liner for each bullet point, don't just casually mention them.

Following this flow with aid in thinking clearly about your project. I hope you have some direction now, so kindly incorporate the changes requested in the issue description.

Last but not the least, kindly refer this issue Crio-Bytes/Miscellaneous#3 for reference.
